package com.example.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AEQ".
*/
public class aeqDao extends AbstractDao<aeq, Long> {

    public static final String TABLENAME = "AEQ";

    /**
     * Properties of entity aeq.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Region = new Property(2, String.class, "region", false, "REGION");
        public final static Property Species = new Property(3, String.class, "species", false, "SPECIES");
        public final static Property Volumetric = new Property(4, Boolean.class, "volumetric", false, "VOLUMETRIC");
        public final static Property PlotID = new Property(5, Long.class, "plotID", false, "PLOT_ID");
    };

    private DaoSession daoSession;

    private Query<aeq> plot_AeqQuery;

    public aeqDao(DaoConfig config) {
        super(config);
    }
    
    public aeqDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AEQ\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"REGION\" TEXT," + // 2: region
                "\"SPECIES\" TEXT," + // 3: species
                "\"VOLUMETRIC\" INTEGER," + // 4: volumetric
                "\"PLOT_ID\" INTEGER);"); // 5: plotID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AEQ\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, aeq entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String region = entity.getRegion();
        if (region != null) {
            stmt.bindString(3, region);
        }
 
        String species = entity.getSpecies();
        if (species != null) {
            stmt.bindString(4, species);
        }
 
        Boolean volumetric = entity.getVolumetric();
        if (volumetric != null) {
            stmt.bindLong(5, volumetric ? 1L: 0L);
        }
 
        Long plotID = entity.getPlotID();
        if (plotID != null) {
            stmt.bindLong(6, plotID);
        }
    }

    @Override
    protected void attachEntity(aeq entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public aeq readEntity(Cursor cursor, int offset) {
        aeq entity = new aeq( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // region
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // species
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // volumetric
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // plotID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, aeq entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRegion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSpecies(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVolumetric(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setPlotID(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(aeq entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(aeq entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "aeq" to-many relationship of Plot. */
    public List<aeq> _queryPlot_Aeq(Long plotID) {
        synchronized (this) {
            if (plot_AeqQuery == null) {
                QueryBuilder<aeq> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlotID.eq(null));
                plot_AeqQuery = queryBuilder.build();
            }
        }
        Query<aeq> query = plot_AeqQuery.forCurrentThread();
        query.setParameter(0, plotID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlotDao().getAllColumns());
            builder.append(" FROM AEQ T");
            builder.append(" LEFT JOIN PLOT T0 ON T.\"PLOT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected aeq loadCurrentDeep(Cursor cursor, boolean lock) {
        aeq entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Plot plot = loadCurrentOther(daoSession.getPlotDao(), cursor, offset);
        entity.setPlot(plot);

        return entity;    
    }

    public aeq loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<aeq> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<aeq> list = new ArrayList<aeq>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<aeq> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<aeq> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
